Cleaner configuration management
webmachine/webmachine pull request #274
Opened 2016-10-15 15:05 UTC by joedevivo

* put explicit defaults in app.src
* don't recompute Server header per request
* Pull webmachine version for Server header from application metadata

Despite the branch name, it turns out that I just did some cleanup that could lead to lager3 in the future.

2016-10-15 20:44 UTC, seancribbs requested changes
Minor nitpicks, yadda yadda

2016-10-15 20:44 UTC, seancribbs commented on src/webmachine_mochiweb.erl
> +            {ok, undefined} ->
Is this `{ok, undefined}` or just `undefined`?

2016-10-15 20:44 UTC, seancribbs commented on src/webmachine_app.erl
> +            "MochiWeb/1.1 WebMachine/~s (~s)",
We should probably produce the correct mochiweb version while we're at it.

2016-10-15 20:44 UTC, seancribbs commented on src/webmachine_mochiweb.erl
> +            {ok, undefined} ->
Oh, I see that you're setting it to undefined in the app.src.

2016-10-15 23:19 UTC, joedevivo commented on src/webmachine_app.erl
> +            "MochiWeb/1.1 WebMachine/~s (~s)",
Pushed, although hopefully we'll need to dynamically determine whether to include MochiWeb at all here :D

2016-10-15 23:20 UTC, joedevivo commented on src/webmachine_mochiweb.erl
> +            {ok, undefined} ->
No implied configuration! :D

2016-10-17 14:42 UTC, seancribbs approved these changes
MOCHIWEB'D!!!!

2016-10-17 14:42 UTC, merged